### ISSUE TITLE
Final Corrections

### ISSUE THREAD

**Issue by VanPaitin** [andela-mpitan/my-bucketlist#8]
## Style guides

Some methods in the user controller and test files do not follow the andela style guide
## Inappropriate arguments

Try to change the controller names to ones that do not reflect the version so versioning will not throw any hassles.
## Bucketlist Factory

The Search bucketlist test file can be refactored to properly take advantage of **FactoryGirl** methods
## Vague Test descriptions

The test documentation is not very descriptive

**Comment by andela-mpitan** [comment]
All issues have been fixed. Thanks for the suggestions
